### ISSUE TITLE
Save multiple user fields for session

### ISSUE THREAD

**Issue by lironess** [saintedlama/passport-local-mongoose#122]
Hi.
As I've seen [here](https://github.com/saintedlama/passport-local-mongoose/blob/master/index.js#L215) you can save at the request session only the username.
Assume I have more information to save - like the role of the user (admin, ordinary user ...) and I want to be able to ask for every request if the user has permissions. I would have to get that information from the session.

I want to be able to save more than the username itself to the session - to serialize multiple fields.
Thanks

**Comment by saintedlama** [comment]
What get's saved in the session is a minimum identifier to allow deserializing the user object. In this case username. If you want to save more for what reason ever since passport-local-mongoose deserializes the whole user object from mongodb, you could just provide your own `serializeUser` and `deserializeUser` functions and use these functions when configuring passport
