### ISSUE TITLE
Change password - verifying old password

### ISSUE THREAD

**Issue by Gentlee** [saintedlama/passport-local-mongoose#127]
User needs to enter old and new password to change it, so how should i verify old password? Method `setPassword` doesn't have `oldPassword` parameter.

**Comment by PunkHaz4rd** [comment]
+1
This is critical

**Comment by mrsteele** [comment]
I wanted to +1 this as well.

I think the closest thing to get this to work right is to do the `schema.methods.authenticate` and if that passes, run the `schema.methods.setPassword`, however the problem is that the `authenticate` method runs through an entire process of logging in, which would be overkill for this feature.

**Comment by saintedlama** [comment]
Newest npm version added a `changePassword` functionality. See api doc in the README
