### ISSUE TITLE
How can I use both username or email id ?

### ISSUE THREAD

**Issue by sundavu** [saintedlama/passport-local-mongoose#196]
I currently use the "username" field to authenticate. Wanted to know how I can use so that a user can use either a username/email to login. I see that the statistics method looks for "username" field only. I want to be able to use passport.use(new LocalStrategy( User.authenticate())); with both fields ?

Thanks

**Comment by jmaister** [comment]
It's in the main options:

usernameQueryFields: specifies alternative fields of the model for identifying a user (e.g. email).

**Comment by jacobarriola** [comment]
@jmaister I added `usernameQueryFields` to the options in order to support email login (in addition to the default username), but I am getting a `400 Bad Request` response.

`userSchema.plugin(passportLocalMongoose, { usernameQueryFields: ['email'] });`

`exports.login = passport.authenticate('local', { sessions: false });`

FYI, when I set `usernameField: 'email'`, it works as expected. However, logging via username does not work. So it seems as though I can only pass either email or username when trying have a user login.

Thanks in advance for the help!

**Comment by cfust** [comment]
@jacobarriola Not sure if that's the best solution but you could manually enter it in.

```
// add passport functions
// schema.plugin(passportLocalMongoose);
schema.plugin(passportLocalMongoose, {
    // allow sign in with username OR email
    findByUsername: function(model, queryParameters) {
        // start
        // // queryParameters => { '$or' : [ { 'username' : 'searchString' } ] }
        // iterate through queryParameters
        for( let param of queryParameters.$or ){
            // if there is a username
            if( typeof param == "object" && param.hasOwnProperty("username") ){
                // add it as an email parameter
                queryParameters.$or.push( { email : param.username } );
            }
        }
        // expected outcome
        // queryParameters => { '$or' : [ { 'username' : 'searchString' }, { 'email' : 'searchString' } ] }
        return model.findOne(queryParameters);
    }
});
```

**Comment by filigino** [comment]
@jacobarriola I was also getting a `400 Bad Request` response until I started sending the email over under the username field:
`{
    "username": "example@gmail.com",
    "password": "password"
}`
This worked for me, so I am able to log in by using either the username or email.
