### ISSUE TITLE
change password for a user (not the connected user)

### ISSUE THREAD

**Issue by prtome** [saintedlama/passport-local-mongoose#77]
Hello
In my settings users cannot modify their password, but the superuser does it for them.
The easiest way I found is to delete the user and recreate it  (ok that is the lazy way).
I am not 100% percent sure I understand the setPassword method: I give it a password, it gives me back a crypted password ? if I use it with my Accounts model as Accounts.setPassword is sets the password for the current user ? right ?  Is there a way of passing the username so that it is that one that is modified ?
What would be the most correct way to do this ? Thanks

**Comment by saintedlama** [comment]
The `setPasspord` function is defined as instance function/method of a model so for your use case you'll need to implement the steps

1) load model
2) invoke `setPassword`
3) save the model since this is not done by `setPassword` directly

Let's assume your model is required as `User`

```javascript
User.findByUsername(username, function(err, user) {
  if (err) { return cb(err); }

  if (!user) {
    return cb(new Error('User does not exist');
  }

  user.setPassword(newPasspord, function(err, user) {
    if (err) {
      return cb(err);
    }

    user.save(function(err) {
      if (err) {
        return cb(err);
      }

      cb(null, user);
     });
   });
  });
```

You can find a similar implementation in the `register` function https://github.com/saintedlama/passport-local-mongoose/blob/master/lib/passport-local-mongoose.js#L164

**Comment by prtome** [comment]
Thank you. I had seen that link (register) and was not writing things correctly. I now understand better what is going on - and have implemented it and it works!
Thanks again for your help and for this library!
