### ISSUE TITLE
Two models based on two separate schemas.

### ISSUE THREAD

**Issue by DanielDeychakiwsky** [saintedlama/passport-local-mongoose#95]
Hi,

This module is fantastic. 

I have two mongoose schemas for two separate users. The schemas contain different data from each other, this wasn't as simple as using the concept of "roles". 

Is there a way to use passport-local-mongoose with two different models? When I require in the module, it is a singleton (from require)....

For instance:

```
// requires the model with Passport-Local Mongoose plugged in
var User = require('./models/user');

// TODO: Auth this user-type as well
var User2 = require('./modles/user2'); 

// use static authenticate method of model in LocalStrategy
passport.use(new LocalStrategy(User.authenticate()));

// use static serialize and deserialize of model for passport session support
passport.serializeUser(User.serializeUser());
passport.deserializeUser(User.deserializeUser());
```

**Comment by saintedlama** [comment]
The problem you describe is more a passport strategy problem because strategies in passport are looked up by name which defines the singleton.

I would suggest to solve the problem by implementing your own `LocalStrategy` that does nothing but hand over authenticate requests to `User` and `User2` model. In case a user can be authenticated against a model everything is fine. In case a user cannot be authenticated against `User` and `User2` model you hand out an error. The same implementation idea could be used for `serializeUser` and `deserializeUser` implementations.

**Comment by DanielDeychakiwsky** [comment]
Thanks for the response!

**Comment by harshmittal-cyber** [comment]
@deychak Hey can u send me your code of serialize user and deseralize user??
